### ISSUE TITLE
Websocket transfer issues

### ISSUE THREAD

**Issue by pandeiro** [pandeiro/bootcamp#1]
Repository info is not making it back to the server from the client.

Additionally, there are occasional exceptions being thrown, eg:

```
Exception in thread "async-dispatch-50" java.lang.UnsupportedOperationException: nth not supported on this type: PersistentHashMap
    at clojure.lang.RT.nthFrom(RT.java:857)
    at clojure.lang.RT.nth(RT.java:807)
    at backend.services.github$merge_if_newer.invoke(github.clj:93)
    at clojure.lang.Atom.swap(Atom.java:51)
    at clojure.core$swap_BANG_.invoke(core.clj:2233)
    at backend.services.github$add_repo_info_BANG_.invoke(github.clj:110)
    at backend.services.github$start_worker$fn__8520$fn__8656$state_machine__5229__auto____8657$fn__8659.invoke(github.clj:130)
    at backend.services.github$start_worker$fn__8520$fn__8656$state_machine__5229__auto____8657.invoke(github.clj:130)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
    at clojure.core.async.impl.ioc_macros$take_BANG_$fn__5245.invoke(ioc_macros.clj:953)
    at clojure.core.async.impl.channels.ManyToManyChannel$fn__933.invoke(channels.clj:133)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by pandeiro** [comment]
While we're at it, there's this:

```
Fri Jan 30 17:36:53 BRST 2015 [worker-2] ERROR - handle websocket frame org.httpkit.server.Frame$TextFrame@53d6a268
java.lang.AssertionError: Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.
(< (.size puts) impl/MAX-QUEUE-SIZE)
    at clojure.core.async.impl.channels.ManyToManyChannel.put_BANG_(channels.clj:150)
    at clojure.core.async$put_BANG_.invoke(async.clj:145)
    at backend.socket$socket_handler$fn__8307.invoke(socket.clj:37)
    at org.httpkit.server.AsyncChannel.messageReceived(AsyncChannel.java:166)
    at org.httpkit.server.WSHandler.run(RingHandler.java:140)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:120)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at org.httpkit.server.LinkingRunnable.run(RingHandler.java:122)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Why are these puts piling up?

**Comment by pandeiro** [comment]
And there's also this, possibly related to [httpkit #179](https://github.com/http-kit/http-kit/issues/179):

```
Sun Feb 01 11:36:44 BRST 2015 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
[Sun Feb 01 11:36:44 BRST 2015] INFO Current websocket connections: 0
[Sun Feb 01 11:36:44 BRST 2015] INFO Socket closed: :unknown
```

TODO: verify the size of all messages being sent from the client to the server
